blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogUpdateView, BlogListView, BlogDetailView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('list/', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    # заголовок, slug, содержимое, превью, дата создания, признак публикации, количество просмотров
    # создаем поля и прописываем их параметры
    title = models.CharField(
        max_length=100,
        verbose_name="заголовок",
        help_text="введите название заголовка",
    )
    slug = models.CharField(
        max_length=100,
        verbose_name="Идентификатор",
        unique=True,
        null=True,
    )
    content = models.TextField(
        max_length=100, verbose_name="содержимое", help_text="Введите содержимое"
    )
    preview = models.ImageField(
        upload_to="catalog/image",
        blank=True,
        null=True,
        verbose_name="изображение",
        help_text="загрузите изображение"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="дата создания",
        help_text="Укажите дату создания"
    )
    published = models.BooleanField(
        default=False,
        verbose_name="публикация",
        help_text="поставьте галочку если статья опубликована"
    )
    views = models.IntegerField(
        default=0,
        verbose_name="Количество просмотров",
        help_text="Укажите количество просмотров"
    )

    class Meta:
        verbose_name = "Запись в блоге"
        verbose_name_plural = "Записи в блоге"

    # строковое представление объекта
    def __str__(self):
        return f"{self.title}"

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ['title', 'content', 'preview', 'published']
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        object_publ = Blog.objects.filter(published=True)
        context['object_publ'] = object_publ
        return context

class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ['title', 'content', 'preview', 'published', ]

    def get_success_url(self):
        return reverse_lazy('blog:blog_view', kwargs={'pk': self.object.id})


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="container">
    <div class="row text">
        <div class="col-12">
            <div class="row">
                <div class="col-4">
                    <div class="card">
                        <p class="p-3 border bg-light">Действительно удалить {{ object.title }} ?</p>
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Удалить</button>
                                <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-10">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }} </h4>
                </div>
                <div class="card-body">
                    <img class="card-img-top" src="{{ object.preview | media_filter }}">
                    <p class="card-text"> Ссылка: {{ object.slug }}</p>
                    <p class="card-text">Содержимое: {{ object.content }}</p>
                    <p class="card-text">Дата создания: {{ object.created_at }}</p>
                    <p class="card-text">Кол-во просмотров: {{ object.views }}</p>
                    <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="container">
    <div class="row text">
        <div class="col-12">
            <div class="row">
                <div class="col-8">
                    <div class="card">
                        <div class="card-body">
                            <form class ="text-body-color mb-3 form-control" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">
                                    {% if object %}
                                        Сохранить
                                    {% else %}
                                        Создать
                                    {% endif %}
                                </button>
                                <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <a class="btn btn-outline-primary mx-auto" href="{% url 'blog:blog_create' %}">Создать блог</a>
        <div class="pb-4"></div>
        {% for object in object_publ %}
            <div class="col-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                    </div>
                    <div class="card-body">
                        <img class="card-img-top" src="{{ object.preview | media_filter }}" width="300" height="400">
                        <p class="text-start">{{ object.content }}</p>
                        <h1 class="card-title pricing-card-title"></h1>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-primary" href="{% url 'blog:blog_view' object.id %}"
                                   role="button">Подробнее</a>
                                <a class="btn btn-sm btn-outline-success" href="{% url 'blog:blog_update' object.id %}"
                                   role="button">Изменить</a>
                                <a class="btn btn-sm btn-outline-danger" href="{% url 'blog:blog_delete' object.id %}"
                                   role="button">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}